kind: pipeline
type: kubernetes
name: default

steps:
- name: Build-wasm
  image: rust:1.66
  commands:
    - cargo install wasm-pack
    - >
      wasm-pack build
      --scope=mellena1
      --target=nodejs
      --release

- name: Publish-to-npm
  image: plugins/npm
  settings:
    username: mellena1
    token:
      from_secret: npm_token
    email: andrew.mellen7@gmail.com
    folder: ./pkg
    access: public
